#
options nvidia NVreg_PreserveVideoMemoryAllocations=1\
    NVreg_TemporaryFilePath="/var/tmp" \
    NVreg_DynamicPowerManagement="0x03" \
    NVreg_UsePageAttributeTable=1 \
    NVreg_InitializeSystemMemoryAllocations=0 \
    NVreg_EnableS0ixPowerManagement=1 \
    NVreg_RegistryDwords=RMIntrLockingMode=1 \
    NVreg_EnableNonblockingOpen=0
